openapi: '3.0.1'
info:
  title: 'screen-geometry-app-backend-serverless-apis-v1'
  version: '3.0.0'
servers:
  - url: 'https://{environment}.typicode.com:{port}/{path}'
    variables:
      environment:
        default: jsonplaceholder
        enum:
          - jsonplaceholder
          - api
          - dev
          - staging
      port:
        enum:
          - '443'
          - '8443'
        default: '443'
      path:
        default: 'v1'
        enum:
          - 'v1'
paths:
  /search:
    get:
      tags:
        - 'search list service'
      parameters:
        - name: 'limit'
          in: 'query'
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - name: 'offset'
          in: 'query'
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: 'sort'
          in: 'query'
          required: false
          schema:
            type: string
            enum:
              - 'name'
              - 'size'
            default: 'name'
        - name: 'order'
          in: 'query'
          required: false
          schema:
            type: string
            enum:
              - 'asc'
              - 'desc'
            default: 'asc'
        - name: term
          in: query
          required: false
          schema:
            type: string
            example: 'WQHD'
      responses:
        '200':
          description: '200 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchListResponse'
              example:
                list:
                  - id: 'WQHD3421:9'
                    name: WQHD
                    label: 'WQHD 34" 3440x1440 21:9'
                    aspectRatio: '21:9'
                    diagonalSize: 34
                    vRes: 1440
                    hRes: 3440
                  - id: 'WQHD+3821:9'
                    name: WQHD+
                    label: 'WQHD+ 38" 3840x1600 21:9'
                    aspectRatio: '21:9'
                    diagonalSize: 38
                    vRes: 1600
                    hRes: 3840
                  - id: '4KUHD2716:9'
                    name: 4K UHD
                    label: '4K UHD 27" 3840x2160 16:9'
                    aspectRatio: '16:9'
                    diagonalSize: 27
                    vRes: 2160
                    hRes: 3840
                  - id: '4KUHD3216:9'
                    name: 4K UHD
                    label: '4K UHD 32" 3840x2160 16:9'
                    aspectRatio: '16:9'
                    diagonalSize: 32
                    vRes: 2160
                    hRes: 3840
        '400':
          description: '400 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: '401 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: '403 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '408':
          description: '408 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '415':
          description: '415 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: '429 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: '503 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - authorizer-api-v2: []
        - api_key: []
      operationId: 'getSearchList'
    options:
      tags:
        - 'search list service'
      responses:
        '200':
          description: '200 response'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
      operationId: 'optionsSearchList'
  /screens:
    get:
      tags:
        - 'screen list service'
      responses:
        '200':
          description: '200 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScreenListResponse'
              example:
                list:
                  - id: pVesw1Iu
                    tag:
                      diagonalSize: 34
                      aspectRatio: '21:9'
                    data:
                      hSize: 31.25093102061397
                      vSize: 13.3932561516917
                      hAspectRatio: 21
                      vAspectRatio: 9
                    spec:
                      hRes: 3440
                      vRes: 1440
                      ppi: 109.68340725465096
                    color:
                      lightColor: '#FCDF50'
                      darkColor: '#967E03'
                    visible: true
                  - id: 5HjERJbH
                    tag:
                      diagonalSize: 38
                      aspectRatio: '21:9'
                    data:
                      hSize: 34.9275111406862
                      vSize: 14.968933346008372
                      hAspectRatio: 21
                      vAspectRatio: 9
                    spec:
                      hRes: 3840
                      vRes: 1600
                      ppi: 109.47368421052632
                    color:
                      lightColor: '#F6693C'
                      darkColor: '#C33609'
                    visible: true
                  - id: LnAg4nPQ
                    tag:
                      diagonalSize: 27
                      aspectRatio: '16:9'
                    data:
                      hSize: 23.53253950236283
                      vSize: 13.237053470079092
                      hAspectRatio: 16
                      vAspectRatio: 9
                    spec:
                      hRes: 3840
                      vRes: 2160
                      ppi: 163.17830889498507
                    color:
                      lightColor: '#67E5AA'
                      darkColor: '#168350'
                    visible: true
                  - id: oxrH4rCU
                    tag:
                      diagonalSize: 49
                      aspectRatio: '32:9'
                    data:
                      hSize: 47.169896067541046
                      vSize: 13.26653326899592
                      hAspectRatio: 32
                      vAspectRatio: 9
                    spec:
                      hRes: 5120
                      vRes: 1440
                      ppi: 108.54380498674065
                    color:
                      lightColor: '#64E8DD'
                      darkColor: '#14857B'
                    visible: true
        '400':
          description: '400 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: '401 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: '403 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '408':
          description: '408 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '415':
          description: '415 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: '429 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: '503 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - authorizer-api-v2: []
        - api_key: []
      operationId: 'getScreenList'
    post:
      tags:
        - 'screen list service'
      requestBody:
        description: Generating a list of ScreenItem objects
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScreenInputList'
      responses:
        '200':
          description: '200 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScreenListResponse'
              example:
                list:
                  - id: pVesw1Iu
                    tag:
                      diagonalSize: 34
                      aspectRatio: '21:9'
                    data:
                      hSize: 31.25093102061397
                      vSize: 13.3932561516917
                      hAspectRatio: 21
                      vAspectRatio: 9
                    spec:
                      hRes: 3440
                      vRes: 1440
                      ppi: 109.68340725465096
                    color:
                      lightColor: '#FCDF50'
                      darkColor: '#967E03'
                    visible: true
                  - id: 5HjERJbH
                    tag:
                      diagonalSize: 38
                      aspectRatio: '21:9'
                    data:
                      hSize: 34.9275111406862
                      vSize: 14.968933346008372
                      hAspectRatio: 21
                      vAspectRatio: 9
                    spec:
                      hRes: 3840
                      vRes: 1600
                      ppi: 109.47368421052632
                    color:
                      lightColor: '#F6693C'
                      darkColor: '#C33609'
                    visible: true
                  - id: LnAg4nPQ
                    tag:
                      diagonalSize: 27
                      aspectRatio: '16:9'
                    data:
                      hSize: 23.53253950236283
                      vSize: 13.237053470079092
                      hAspectRatio: 16
                      vAspectRatio: 9
                    spec:
                      hRes: 3840
                      vRes: 2160
                      ppi: 163.17830889498507
                    color:
                      lightColor: '#67E5AA'
                      darkColor: '#168350'
                    visible: true
                  - id: oxrH4rCU
                    tag:
                      diagonalSize: 49
                      aspectRatio: '32:9'
                    data:
                      hSize: 47.169896067541046
                      vSize: 13.26653326899592
                      hAspectRatio: 32
                      vAspectRatio: 9
                    spec:
                      hRes: 5120
                      vRes: 1440
                      ppi: 108.54380498674065
                    color:
                      lightColor: '#64E8DD'
                      darkColor: '#14857B'
                    visible: true
        '400':
          description: '400 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: '401 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: '403 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '408':
          description: '408 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '415':
          description: '415 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: '429 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: '503 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - authorizer-api-v2: []
        - api_key: []
      operationId: 'createScreenList'
    options:
      tags:
        - 'screen list service'
      responses:
        '200':
          description: '200 response'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
      operationId: 'optionsScreenList'
  /screen:
    post:
      tags:
        - 'screen service'
      requestBody:
        description: Primitive for generating a ScreenItem object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScreenInput'
      responses:
        '200':
          description: '200 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScreenItemResponse'
              example:
                item:
                  id: ttUL6ooF
                  tag:
                    diagonalSize: 49
                    aspectRatio: '32:9'
                  data:
                    hSize: 47.169896067541046
                    vSize: 13.26653326899592
                    hAspectRatio: 32
                    vAspectRatio: 9
                  spec:
                    hRes: 5120
                    vRes: 1440
                    ppi: 108.54380498674065
                  color:
                    lightColor: '#64E8DD'
                    darkColor: '#14857B'
                  visible: true
                  render:
                    width: 1
                    height: 0.6293053673644803
        '400':
          description: '400 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: '401 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: '403 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '408':
          description: '408 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '415':
          description: '415 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: '429 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: '503 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - authorizer-api-v2: []
        - api_key: []
      operationId: 'createScreen'
    options:
      tags:
        - 'screen list service'
      responses:
        '200':
          description: '200 response'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
      operationId: 'optionsCreateScreen'
  /screen/{id}/show:
    patch:
      tags:
        - 'screen service'
      parameters:
        - name: 'id'
          in: 'path'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: '200 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScreenItemResponse'
              example:
                item:
                  id: 5HjERJbH
                  tag:
                    diagonalSize: 38
                    aspectRatio: '21:9'
                  data:
                    hSize: 34.9275111406862
                    vSize: 14.968933346008372
                    hAspectRatio: 21
                    vAspectRatio: 9
                  spec:
                    hRes: 3840
                    vRes: 1600
                    ppi: 109.47368421052632
                  color:
                    lightColor: '#F6693C'
                    darkColor: '#C33609'
                  visible: false
                  render:
                    width: 0.7404619058450888
                    height: 0.7100596596986617
        '400':
          description: '400 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: '401 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: '403 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '408':
          description: '408 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '415':
          description: '415 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: '429 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: '503 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - authorizer-api-v2: []
        - api_key: []
      operationId: 'showScreen'
    options:
      parameters:
        - name: 'id'
          in: 'path'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: '200 response'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
      operationId: 'optionsShowScreen'
  /screen/{id}:
    get:
      tags:
        - 'screen service'
      parameters:
        - name: 'id'
          in: 'path'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: '200 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScreenItemResponse'
              example:
                item:
                  id: 5HjERJbH
                  tag:
                    diagonalSize: 38
                    aspectRatio: '21:9'
                  data:
                    hSize: 34.9275111406862
                    vSize: 14.968933346008372
                    hAspectRatio: 21
                    vAspectRatio: 9
                  spec:
                    hRes: 3840
                    vRes: 1600
                    ppi: 109.47368421052632
                  color:
                    lightColor: '#F6693C'
                    darkColor: '#C33609'
                  visible: true
                  render:
                    width: 0.7404619058450888
                    height: 0.7100596596986617
        '400':
          description: '400 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: '401 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: '403 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '408':
          description: '408 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '415':
          description: '415 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: '429 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: '503 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - authorizer-api-v2: []
        - api_key: []
      operationId: 'getScreen'
    put:
      tags:
        - 'screen service'
      parameters:
        - name: 'id'
          in: 'path'
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent screen in list
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScreenInput'
      responses:
        '200':
          description: '200 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScreenItemResponse'
              example:
                item:
                  id: 5HjERJbH
                  tag:
                    diagonalSize: 38
                    aspectRatio: '21:9'
                  data:
                    hSize: 34.9275111406862
                    vSize: 14.968933346008372
                    hAspectRatio: 21
                    vAspectRatio: 9
                  spec:
                    hRes: 3840
                    vRes: 1600
                    ppi: 109.47368421052632
                  color:
                    lightColor: '#F6693C'
                    darkColor: '#C33609'
                  visible: true
                  render:
                    width: 0.7404619058450888
                    height: 0.7100596596986617
        '400':
          description: '400 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: '401 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: '403 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '408':
          description: '408 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '415':
          description: '415 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: '429 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: '503 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - authorizer-api-v2: []
        - api_key: []
      operationId: 'updateScreen'
    delete:
      tags:
        - 'screen service'
      parameters:
        - name: 'id'
          in: 'path'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: '200 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScreenIdResponse'
              example:
                id: 5HjERJbH
        '400':
          description: '400 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: '401 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: '403 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '408':
          description: '408 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '415':
          description: '415 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: '429 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: '503 response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - authorizer-api-v2: []
        - api_key: []
      operationId: 'deleteScreen'
    options:
      tags:
        - 'screen service'
      parameters:
        - name: 'id'
          in: 'path'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: '200 response'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
      operationId: 'optionsScreen'
components:
  schemas:
    SearchListResponse:
      required:
        - 'list'
      type: object
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/SearchItem'
    SearchItem:
      required:
        - 'id'
        - 'name'
        - 'label'
        - 'aspectRatio'
        - 'hRes'
        - 'vRes'
      type: object
      properties:
        id:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        label:
          type: string
          minLength: 1
        aspectRatio:
          type: string
          minLength: 3
        diagonalSize:
          type: number
          minimum: 0
          exclusiveMinimum: true
        hRes:
          type: number
          minimum: 0
          exclusiveMinimum: true
        vRes:
          type: number
          minimum: 0
          exclusiveMinimum: true
      description: 'Complete search object'
    ScreenListResponse:
      required:
        - 'list'
      type: object
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/ScreenItem'
    ScreenIdResponse:
      required:
        - 'id'
      type: object
      properties:
        id:
          type: string
    ScreenItemResponse:
      required:
        - 'item'
      type: object
      properties:
        item:
          $ref: '#/components/schemas/ScreenItem'
    ScreenItem:
      required:
        - 'id'
        - 'tag'
        - 'data'
        - 'color'
        - 'visible'
      type: object
      properties:
        id:
          type: string
          minLength: 1
        visible:
          type: boolean
        tag:
          $ref: '#/components/schemas/ScreenTag'
        data:
          $ref: '#/components/schemas/ScreenData'
        color:
          $ref: '#/components/schemas/ScreenColor'
        spec:
          $ref: '#/components/schemas/ScreenSpec'
        render:
          $ref: '#/components/schemas/ScreenRender'
      description: 'Complete screen object'
    ScreenInputList:
      type: array
      items:
        $ref: '#/components/schemas/ScreenInput'
    ScreenTag:
      required:
        - 'diagonalSize'
        - 'aspectRatio'
      type: object
      properties:
        diagonalSize:
          type: number
          minimum: 0
          exclusiveMinimum: true
        aspectRatio:
          type: string
          minLength: 3
      description: 'Screen primitive data'
    ScreenInput:
      required:
        - 'diagonalSize'
        - 'aspectRatio'
        - 'lightColor'
        - 'darkColor'
      type: object
      properties:
        diagonalSize:
          type: number
          nullable: true
          minimum: 0
          exclusiveMinimum: true
        aspectRatio:
          minLength: 3
          nullable: true
          type: string
        lightColor:
          type: string
          minLength: 7
          maxLength: 7
          pattern: '#([a-f0-9]{6})\b'
        darkColor:
          type: string
          minLength: 7
          maxLength: 7
          pattern: '#([a-f0-9]{6})\b'
        hRes:
          type: integer
          nullable: true
          minimum: 0
          exclusiveMinimum: true
        vRes:
          type: number
          nullable: true
      description: 'Screen primitive data'
    ScreenData:
      required:
        - 'hSize'
        - 'vSize'
        - 'hAspectRatio'
        - 'vAspectRatio'
      type: object
      properties:
        hSize:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        vSize:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        hAspectRatio:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        vAspectRatio:
          type: integer
          minimum: 0
          exclusiveMinimum: true
      description: 'Screen physical characteristics'
    ScreenSpec:
      required:
        - 'hRes'
        - 'vRes'
        - 'ppi'
      type: object
      properties:
        hRes:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        vRes:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        ppi:
          type: number
          minimum: 0
          exclusiveMinimum: true
      description: 'Screen resolution characteristics'
    ScreenRender:
      type: object
      properties:
        width:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        height:
          type: integer
          minimum: 0
          exclusiveMinimum: true
        pixelSize:
          type: integer
          minimum: 0
          exclusiveMinimum: true
      description: 'Screen representation in UI'
    ScreenColor:
      required:
        - 'lightColor'
        - 'darkColor'
      type: object
      properties:
        lightColor:
          type: string
          minLength: 7
          maxLength: 7
          pattern: '#([a-f0-9]{6})\b'
        darkColor:
          type: string
          minLength: 7
          maxLength: 7
          pattern: '#([a-f0-9]{6})\b'
      description: 'Screen representation colors in hex format'
    ErrorResponse:
      required:
        - 'error'
      type: object
      properties:
        error:
          required:
            - 'code'
            - 'status'
          type: object
          properties:
            code:
              type: number
            message:
              minLength: 1
              type: string
            status:
              minLength: 1
              type: string
            details:
              type: object
              properties:
                reason:
                  minLength: 1
                  type: string
                domain:
                  minLength: 1
                  type: string
                metadata:
                  type: object
      description: ''
  securitySchemes:
    api_key:
      type: 'apiKey'
      name: 'x-api-key'
      in: 'header'
    authorizer-api-v2:
      type: 'apiKey'
      name: 'Authorization'
      in: 'header'
      x-amazon-apigateway-authtype: 'custom'
x-amazon-apigateway-policy:
  Version: '1.0.0'
  Statement:
    - Effect: 'Allow'
      Principal: '*'
      Action: 'execute-api:Invoke'
      Resource: 'arn:aws:execute-api:ap-southeast-1:123456789012:abcdefabcd/*/*/*'
